### ISSUE TITLE
Commends can be edited by everyone 

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/BlogGenerator#1]
Currently commends can be edited by everyone.
I don't think this is a good idea. This way we can not ensure weather a commend is genuine or not.

![bildschirmfoto vom 2017-12-23 15-33-42](https://user-images.githubusercontent.com/1891273/34320282-ef34c6b6-e7f6-11e7-9206-b666a1941648.png)

**Comment by TobiGr** [comment]
afaik you can only edit the comment for 10 minutes with the same browser and IP address. I will take a look at the docs to see whether I am right or not.

**Comment by TobiGr** [comment]
The docs for server configuration say:
> time range that allows users to edit/remove their **own** comments.
It supports years, weeks, days, hours, minutes, seconds.
3h45m12s equals to 3 hours, 45 minutes and 12 seconds.
default: max-age = 15m

So no need to worry :)
@theScrabi By the way, we don't use this repo any more as all three parts of the website are in the website repository now.

**Comment by theScrabi** [comment]
ah I see. So we could also delete this repo then :)
